### ISSUE TITLE
Description changed

### ISSUE THREAD

**Issue by deepaksy** [pixan198/test_repo#4]
Change Description in test.md file.

**Comment by pixan198** [comment]
@deepaksy Why do you want to change the description?

**Comment by deepaksy** [comment]
@pixan198 The description must use simple words. little confusing for me.

**Comment by pixan198** [comment]
@deepaksy Yeah, I think the same.
Can you please suggest something for the description?

**Comment by deepaksy** [comment]
@pixan198 
This is the change i suggest you to do in the repo: -

## This repository is to get beginner's  hands on  working in Github.

**Comment by pixan198** [comment]
@deepaksy Yes, it is good.
Can you make a PR to make the changes!
